package com.hc.model;
// Generated 1 juil. 2016 21:25:32 by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * AleatoireEau generated by hbm2java
 */
public class AleatoireEau implements java.io.Serializable {

	private Integer id;
	private Compte compte;
	private Date dateConsultation;
	private long chiffreCompteur;
	private long quantite;

	public AleatoireEau() {
	}

	public AleatoireEau(Compte compte, long chiffreCompteur, long quantite) {
		this.compte = compte;
		this.chiffreCompteur = chiffreCompteur;
		this.dateConsultation = new Date();
		this.quantite = quantite;
	}

	public AleatoireEau(Compte compte, Date dateConsultation, long chiffreCompteur, long quantite) {
		this.compte = compte;
		this.dateConsultation = dateConsultation;
		this.chiffreCompteur = chiffreCompteur;
		this.quantite = quantite;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Compte getCompte() {
		return this.compte;
	}

	public void setCompte(Compte compte) {
		this.compte = compte;
	}

	public Date getDateConsultation() {
		return this.dateConsultation;
	}

	public void setDateConsultation(Date dateConsultation) {
		this.dateConsultation = dateConsultation;
	}

	public long getChiffreCompteur() {
		return this.chiffreCompteur;
	}

	public void setChiffreCompteur(long chiffreCompteur) {
		this.chiffreCompteur = chiffreCompteur;
	}

	public long getQuantite() {
		return this.quantite;
	}

	public void setQuantite(long quantite) {
		this.quantite = quantite;
	}

}
