package com.hc.model;
// Generated 11 mai 2016 03:02:00 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Compte generated by hbm2java
 */
public class Compte implements java.io.Serializable {

	private Integer id;
	private String login;
	private String pwd;
	private String email;
	private String numCompteur;
	private String cleActivation;
	private Date dateActivation;
	private Set<MensuelleEau> mensuelleEaus = new HashSet<MensuelleEau>(0);
	private Set<AleatoireEau> aleatoireEaus = new HashSet<AleatoireEau>(0);

	public Compte() {
	}

	public Compte(String login, String pwd, String email, String numCompteur, String cleActivation,
			Date dateActivation) {
		this.login = login;
		this.pwd = pwd;
		this.email = email;
		this.numCompteur = numCompteur;
		this.cleActivation = cleActivation;
		this.dateActivation = dateActivation;
	}

	public Compte(String login, String pwd, String email, String numCompteur, String cleActivation, Date dateActivation,
			Set<MensuelleEau> mensuelleEaus, Set<AleatoireEau> aleatoireEaus) {
		this.login = login;
		this.pwd = pwd;
		this.email = email;
		this.numCompteur = numCompteur;
		this.cleActivation = cleActivation;
		this.dateActivation = dateActivation;
		this.mensuelleEaus = mensuelleEaus;
		this.aleatoireEaus = aleatoireEaus;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getLogin() {
		return this.login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	public String getPwd() {
		return this.pwd;
	}

	public void setPwd(String pwd) {
		this.pwd = pwd;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getNumCompteur() {
		return this.numCompteur;
	}

	public void setNumCompteur(String numCompteur) {
		this.numCompteur = numCompteur;
	}

	public String getCleActivation() {
		return this.cleActivation;
	}

	public void setCleActivation(String cleActivation) {
		this.cleActivation = cleActivation;
	}

	public Date getDateActivation() {
		return this.dateActivation;
	}

	public void setDateActivation(Date dateActivation) {
		this.dateActivation = dateActivation;
	}

	public Set<MensuelleEau> getMensuelleEaus() {
		return this.mensuelleEaus;
	}

	public void setMensuelleEaus(Set<MensuelleEau> mensuelleEaus) {
		this.mensuelleEaus = mensuelleEaus;
	}

	public Set<AleatoireEau> getAleatoireEaus() {
		return this.aleatoireEaus;
	}

	public void setAleatoireEaus(Set<AleatoireEau> aleatoireEaus) {
		this.aleatoireEaus = aleatoireEaus;
	}

}
