package com.hc.model;
// Generated 11 mai 2016 03:02:00 by Hibernate Tools 4.3.1.Final

/**
 * Keys generated by hbm2java
 */
public class Keys implements java.io.Serializable {

	private Integer id;
	private String key;

	public Keys() {
	}

	public Keys(String key) {
		this.key = key;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getKey() {
		return this.key;
	}

	public void setKey(String key) {
		this.key = key;
	}

}
