package com.hc.model;
// Generated 11 mai 2016 03:02:00 by Hibernate Tools 4.3.1.Final

/**
 * TrancheAssainissementEau generated by hbm2java
 */
public class TrancheAssainissementEau implements java.io.Serializable {

	private int numero;
	private int de;
	private int a;
	private float prixTtc;
	private float redevance;
	private int idRegion;
	private int idSociete;

	public TrancheAssainissementEau() {
	}

	public TrancheAssainissementEau(int numero, int de, int a, float prixTtc, float redevance, int idRegion,
			int idSociete) {
		this.numero = numero;
		this.de = de;
		this.a = a;
		this.prixTtc = prixTtc;
		this.redevance = redevance;
		this.idRegion = idRegion;
		this.idSociete = idSociete;
	}

	public int getNumero() {
		return this.numero;
	}

	public void setNumero(int numero) {
		this.numero = numero;
	}

	public int getDe() {
		return this.de;
	}

	public void setDe(int de) {
		this.de = de;
	}

	public int getA() {
		return this.a;
	}

	public void setA(int a) {
		this.a = a;
	}

	public float getPrixTtc() {
		return this.prixTtc;
	}

	public void setPrixTtc(float prixTtc) {
		this.prixTtc = prixTtc;
	}

	public float getRedevance() {
		return this.redevance;
	}

	public void setRedevance(float redevance) {
		this.redevance = redevance;
	}

	public int getIdRegion() {
		return this.idRegion;
	}

	public void setIdRegion(int idRegion) {
		this.idRegion = idRegion;
	}

	public int getIdSociete() {
		return this.idSociete;
	}

	public void setIdSociete(int idSociete) {
		this.idSociete = idSociete;
	}

}
