package com.hc.model;
// Generated 11 mai 2016 03:02:00 by Hibernate Tools 4.3.1.Final

/**
 * TrancheTarifElec generated by hbm2java
 */
public class TrancheTarifElec implements java.io.Serializable {

	private int numero;
	private int du;
	private int a;
	private float prixTtc;
	private int idRegion;
	private int idSociete;

	public TrancheTarifElec() {
	}

	public TrancheTarifElec(int numero, int du, int a, float prixTtc, int idRegion, int idSociete) {
		this.numero = numero;
		this.du = du;
		this.a = a;
		this.prixTtc = prixTtc;
		this.idRegion = idRegion;
		this.idSociete = idSociete;
	}

	public int getNumero() {
		return this.numero;
	}

	public void setNumero(int numero) {
		this.numero = numero;
	}

	public int getDu() {
		return this.du;
	}

	public void setDu(int du) {
		this.du = du;
	}

	public int getA() {
		return this.a;
	}

	public void setA(int a) {
		this.a = a;
	}

	public float getPrixTtc() {
		return this.prixTtc;
	}

	public void setPrixTtc(float prixTtc) {
		this.prixTtc = prixTtc;
	}

	public int getIdRegion() {
		return this.idRegion;
	}

	public void setIdRegion(int idRegion) {
		this.idRegion = idRegion;
	}

	public int getIdSociete() {
		return this.idSociete;
	}

	public void setIdSociete(int idSociete) {
		this.idSociete = idSociete;
	}

}
